### ISSUE TITLE
Implement the equivalent of the chainsafe/hardhat-plugin-multichain-deploy plugin using Foundry

### ISSUE THREAD

**Issue by stonecharioteer** [ChainSafe/foundry-multichain-deploy#1]
This tool would help developers work with Sygma in deploying their contracts to multiple blockchains and paying only one centralized gas fee. While this has been implemented for hardhat 
[here](https://github.com/ChainSafe/hardhat-plugin-multichain-deploy), implementing it in foundry would greatly help the Rust blockchain community to program on multiple blockchains.

- [ ] Create a starting repository using the `forge init` command.
- [ ] Copy over the smartcontracts from [hardhat-plugin-multichain-deploy](https://github.com/ChainSafe/hardhat-plugin-multichain-deploy).
- [ ] Test using `forge` and `anvil`
  - [ ] Ensure the tests written for the contract work as they do with hardhat.
- [ ] Deploy on testnets and validate.

Questions - should the solidity files be centralized (perhaps later) so that they are all in one central place and we don't have errors related to versions/updates?

**Comment by mpetrunic** [comment]
I think this integration should br in two parts:
1. Create CrossChainDeployScript contract similar to: https://github.com/ind-igo/forge-safe/blob/main/src/BatchScript.sol
   - it should use CrossChainAdapter interface
   - it should contain hardcoded addresses on each chain
   - it should be able to encode and invoke calls to CrossChainAdapter interface
2. Create CLI to enable users to deploy multichain similar to https://book.getfoundry.sh/reference/forge/forge-create that deploys contract on multiple chains

Maybe best if you separate those 2 in separate issues. Maybe best if you start with 1) and ask oleksii for advice. 

As for CrossChainDeploy contracts, they can be published to npm. Would some other repository be preferable for foundry?

**Comment by mpetrunic** [comment]
@stonecharioteer I think we need another issue for cli :)

**Comment by mpetrunic** [comment]
> Ah yeah, it's just that I'd need a CLI _while_ working on the contracts to test it anyway 🤷🏾‍♂️

not really, scripts are tested using forge script, you don't need our cli to test :)
